version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["[]ğŸ¥ å¥ˆé£èŠ‚ç‚¹","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["[]DIRECT","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

#[[custom_groups]]
#name = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³Playä¸‹è½½"
#type = "select"
#rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

#[[custom_groups]]
#name = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³PlayæœåŠ¡"
#type = "select"
#rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

#[[custom_groups]]
#name = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³PlayæœåŠ¡"
#type = "select"
#rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

#[[custom_groups]]
#name = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³"
#type = "select"
#rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

#[[custom_groups]]
#name = "ğŸ“¢ è°·æ­Œ"
#type = "select"
#rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢","[]DIRECT"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

#[[custom_groups]]
#name = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
#type = "select"
#rule =  ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","(ç½‘æ˜“|éŸ³ä¹|è§£é”|Music|NetEase)"]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©"]

#[[custom_groups]]
#name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
#type = "select"
#rule = ["[]REJECT","[]DIRECT"]

#[[custom_groups]]
#name = "ğŸƒ åº”ç”¨å‡€åŒ–"
#type = "select"
#rule = ["[]REJECT","[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]DIRECT","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£èŠ‚ç‚¹"
type = "select"
rule = ["(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media|åª’ä½“)"]

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

#[[rulesets]]
#group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

#[[rulesets]]
#group = "ğŸƒ åº”ç”¨å‡€åŒ–"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

#[[rulesets]]
#group = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³Playä¸‹è½½"
#ruleset = "[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com"

#[[rulesets]]
#group = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³PlayæœåŠ¡"
#ruleset = "[]DOMAIN-SUFFIX,services.googleapis.cn"

#[[rulesets]]
#group = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³PlayæœåŠ¡"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

#[[rulesets]]
#group = "ğŸ“¢ è°·æ­ŒğŸ‡¨ğŸ‡³"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list"

#[[rulesets]]
#group = "ğŸ“¢ è°·æ­Œ"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

#[[rulesets]]
#group = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "[]GEOIP,LAN"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
